"""Build driver (MSVC).

  python tools/build.py difftest   translate the CRT slice, build and run tests/difftest.c (x86)
  python tools/build.py host       translate everything, build the stand-in FFXiMain.dll and
                                   tests/boot.exe, and run the boot test (x86, R2)
  python tools/build.py boot64     the same translation built for a 64-bit host with the portable
                                   runtime (runtime/portable), and tests/boot64.exe run (x64, R3.1)
  python tools/build.py host64     the 64-bit game host (x64): FFXiMain and FFXi.dll translated, the
                                   portable runtime, SDL3 and the Direct3D 12 back end
  python tools/build.py host64-headless
                                   the same host with no graphics (gfx_null.c), for measuring the
                                   game's CPU time alone: build/host64-headless.exe
  python tools/build.py uwp-lib    host64 as a library for the UWP app (FFXIXbox): build/uwp/ffxi_uwp.lib
  python tools/build.py gfxtest    the Direct3D 12 back end and the D3D8 front end, offscreen, without
                                   the game (tests/gfx_test.c, tests/d3d8_test.c); needs no prepare

Needs generated/FFXiMain.unpacked.dll and generated/build.json (python tools/prepare.py), which
pick the retail build; its addresses go to generated/build.h. Incremental: the recompiler only
rewrites C files whose text changed, and only stale objects are recompiled.
"""
import json
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
import buildinfo  # noqa: E402

# The retail build tools/prepare.py chose (meta/builds.json); None before it has run.
BUILD = buildinfo.current(required=False)
META = BUILD and BUILD['ffximain_meta']  # per-build metadata (from the discovery pass)
IMAGE = os.path.join(ROOT, 'generated', 'FFXiMain.unpacked.dll')
RETAIL = os.path.join(ROOT, 'generated', 'FFXiMain.retail.dll')  # verified copy, written by prepare.py
BUILD_H = os.path.join(ROOT, 'generated', 'build.h')
SLICE = BUILD and ','.join(BUILD['crt'].values())  # the CRT functions tests/difftest.c compares
CFLAGS = ['/nologo', '/O2', '/MT', '/W3', '/std:c11', '/bigobj', '/I', 'runtime', '/I', 'runtime\\win32', '/I',
          'generated']
# 64-bit hosts: guest memory is a window (guest.h) and the runtime is runtime/portable
CFLAGS64 = ['/nologo', '/O2', '/MT', '/W3', '/std:c11', '/bigobj', '/DRT_GUEST_WINDOW', '/I', 'runtime', '/I',
            'runtime\\portable', '/I', 'generated']


def write_build_h():
    """generated/build.h: the addresses of this build that the runtime and tests name directly."""
    lines = ['/* Generated by tools/build.py from meta/builds.json. Do not edit. */', '#pragma once',
             '#define FFXI_BUILD "%s"' % BUILD['build'],
             '#define FFXI_VERSION "%s" /* the version string patch.ver carries */' % BUILD['version']]
    for k, v in BUILD['addresses'].items():
        lines.append('#define FFXI_%s 0x%08xu' % (k.upper(), int(v, 16)))
    for k, v in BUILD['hooks'].items():
        lines.append('#define FFXI_HOOK_%s 0x%08xu /* rt_hook_%s runs here */' % (k.upper(), int(v, 16), k))
    for k, v in BUILD['wraps'].items():
        lines.append('#define FFXI_WRAP_%s 0x%08xu /* rt_wrap_%s may replace this function */' % (k.upper(), int(v, 16), k))
    for k, v in BUILD['crt'].items():
        a = int(v, 16)
        lines.append('#define CRT_%s 0x%08xu' % (k.upper(), a))
        lines.append('#define F_%s f_%08x' % (k.upper(), a))
    # host/modern.c's addresses: FFXI_MODERN is 1 only when this build has every one of them (a
    # build carried without them, or with one unmapped, gets 0 and every address 0: not called).
    modern = BUILD['modern']
    whole = bool(BUILD['modern_keys']) and all(modern.get(k, '').startswith('0x') for k in BUILD['modern_keys'])
    lines.append('#define FFXI_MODERN %d /* Config > Modern and Config > Menus */' % whole)
    for k in BUILD['modern_keys']:
        lines.append('#define FFXI_MODERN_%s 0x%08xu' % (k.upper(), int(modern[k], 16) if whole else 0))
    text = '\n'.join(lines) + '\n'
    try:
        with open(BUILD_H) as f:
            if f.read() == text:
                return
    except OSError:
        pass
    with open(BUILD_H, 'w') as f:
        f.write(text)


PORTABLE =['runtime\\runtime.c', 'runtime\\portable\\plat_win.c', 'runtime\\portable\\gwin.c',
            'runtime\\portable\\gthread.c', 'runtime\\portable\\thunk.c', 'runtime\\portable\\pe.c',
            'runtime\\portable\\k32.c', 'runtime\\portable\\gamecore.c', 'runtime\\portable\\vfs.c',
            'runtime\\portable\\kobj.c', 'runtime\\portable\\k32_io.c', 'runtime\\portable\\gamecore_slots.c',
            'runtime\\portable\\reg.c', 'runtime\\portable\\ole.c', 'runtime\\portable\\gamecore_files.c',
            'runtime\\portable\\k32_misc.c', 'runtime\\portable\\gamecore_presence.c']


def msvc_env(arch='x86'):
    pf = os.environ.get('ProgramFiles(x86)', r'C:\Program Files (x86)')
    vswhere = os.path.join(pf, 'Microsoft Visual Studio', 'Installer', 'vswhere.exe')
    vs = subprocess.check_output([vswhere, '-latest', '-products', '*', '-property', 'installationPath'], text=True).strip()
    vcvars = os.path.join(vs, 'VC', 'Auxiliary', 'Build', 'vcvarsall.bat')
    env = dict(os.environ)
    env['PATH'] = os.path.dirname(vswhere) + ';' + env['PATH']
    out = subprocess.check_output('"%s" %s >nul && set' % (vcvars, arch), shell=True, text=True, env=env)
    for line in out.splitlines():
        if '=' in line:
            k, v = line.split('=', 1)
            env[k] = v
    return env


def run(cmd, env=None):
    print('>', ' '.join(cmd) if len(' '.join(cmd)) < 200 else ' '.join(cmd)[:200] + ' ...')
    if env is not None:
        # CreateProcess searches the parent's PATH, not env's: resolve cl/link against the VS PATH.
        exe = shutil.which(cmd[0], path=env['PATH'])
        if exe:
            cmd = [exe] + cmd[1:]
    if not os.path.isabs(cmd[0]) and os.path.exists(os.path.join(ROOT, cmd[0])):
        cmd = [os.path.join(ROOT, cmd[0])] + cmd[1:]  # relative programs are ours, under ROOT
    subprocess.check_call(cmd, cwd=ROOT, env=env)


def compile_stale(env, sources, objdir, extra, cflags=CFLAGS):
    os.makedirs(os.path.join(ROOT, objdir), exist_ok=True)
    stale = []
    for s in sources:
        obj = os.path.join(ROOT, objdir, os.path.splitext(os.path.basename(s))[0] + '.obj')
        src = os.path.join(ROOT, s)
        if not os.path.exists(obj) or os.path.getmtime(obj) < os.path.getmtime(src):
            stale.append(s)
        elif not s.startswith('generated') and os.path.getmtime(obj) < os.path.getmtime(BUILD_H):
            with open(src, errors='replace') as f:
                if '"build.h"' in f.read():  # another build's addresses
                    stale.append(s)
    if stale:
        print('compiling %d of %d' % (len(stale), len(sources)))
        run(['cl', '/c', '/MP'] + cflags + extra + stale + ['/Fo:%s\\' % objdir], env)
    return [os.path.join(objdir, os.path.splitext(os.path.basename(s))[0] + '.obj') for s in sources]


def recomp(out, extra):
    hooks = ','.join('%s=%s' % kv for kv in BUILD['hooks'].items())  # host hook points (recomp.py --hooks)
    wraps = ','.join('%s=%s' % kv for kv in BUILD['wraps'].items())  # host-replaceable functions (--wraps)
    # addons' code patches, translated as variants (--patches): generated/patches.json
    patches = os.path.join(ROOT, 'generated', 'patches.json')
    text = json.dumps(BUILD['patches'], indent=1, sort_keys=True)
    if not os.path.exists(patches) or open(patches).read() != text:
        with open(patches, 'w') as f:
            f.write(text)
    run([sys.executable, 'recomp/recomp.py', '--meta', META, '--image', IMAGE, '--retail', RETAIL, '--out', out]
        + (['--hooks', hooks] if hooks else []) + (['--wraps', wraps] if wraps else [])
        + (['--patches', patches] if BUILD['patches'] else []) + extra)


def difftest(env):
    recomp('generated/slice', ['--functions', SLICE])
    gen = ['generated\\slice\\' + f for f in sorted(os.listdir(os.path.join(ROOT, 'generated', 'slice'))) if f.endswith('.c')]
    objs = compile_stale(env, gen + ['runtime\\runtime.c', 'tests\\difftest.c'], 'build\\slice', ['/I', 'generated\\slice'])
    run(['link', '/nologo', '/OUT:build\\difftest.exe', '/MACHINE:X86', '/DYNAMICBASE:NO', '/BASE:0x00400000'] + objs, env)
    run(['build\\difftest.exe'], env)


def host(env):
    recomp('generated/all', ['--all'])
    gen = ['generated\\all\\' + f for f in sorted(os.listdir(os.path.join(ROOT, 'generated', 'all'))) if f.endswith('.c')]
    objs = compile_stale(env, gen + ['runtime\\runtime.c', 'runtime\\win32\\bridge.c', 'runtime\\win32\\loader.c',
                                     'host\\ffximain.c'], 'build\\all', ['/I', 'generated\\all'])
    os.makedirs(os.path.join(ROOT, 'build', 'host'), exist_ok=True)
    # Fixed base, out of the way of the game image's preferred 0x10000000 (it may still be relocated).
    run(['link', '/nologo', '/DLL', '/DEF:host\\ffximain.def', '/OUT:build\\host\\FFXiMain.dll', '/MACHINE:X86',
         '/BASE:0x60000000', '/DYNAMICBASE:NO', 'ole32.lib', 'user32.lib', 'synchronization.lib'] + objs, env)
    boot = compile_stale(env, ['tests\\boot.c'], 'build\\boot', [])
    run(['link', '/nologo', '/OUT:build\\boot.exe', '/MACHINE:X86', 'ole32.lib', 'uuid.lib'] + boot, env)
    run(['build\\boot.exe', 'build\\host\\FFXiMain.dll', RETAIL], env)
    run(['build\\boot.exe', 'build\\host\\FFXiMain.dll', RETAIL, 'relocate'], env)  # as inside the retail launcher


def boot64(env):
    recomp('generated/all', ['--all'])
    gen = ['generated\\all\\' + f for f in sorted(os.listdir(os.path.join(ROOT, 'generated', 'all'))) if f.endswith('.c')]
    objs = compile_stale(env, gen + PORTABLE + ['tests\\boot64.c'], 'build\\all64', ['/I', 'generated\\all'], CFLAGS64)
    run(['link', '/nologo', '/OUT:build\\boot64.exe', '/MACHINE:X64', 'synchronization.lib'] + objs, env)
    # the game's registry keys, as a Mac player would bring them (build/ is gitignored)
    reg = os.path.join(ROOT, 'build', 'ffxi.reg')
    subprocess.call(['reg', 'export', r'HKLM\SOFTWARE\WOW6432Node\PlayOnlineUS', reg, '/y'], stdout=subprocess.DEVNULL)
    run(['build\\boot64.exe', RETAIL, BUILD['game']] + ([reg] if os.path.exists(reg) else []), env)


FFXI_META = BUILD and BUILD['ffxi_meta']
FFXI_IMAGE = os.path.join(ROOT, 'generated', 'FFXi.unpacked.dll')  # written by tools/prepare.py
FFXI_RETAIL = os.path.join(ROOT, 'generated', 'FFXi.retail.dll')
SDL3 = os.environ.get('SDL3_DIR', r'C:\Dev\SDL3\SDL3-3.4.16')  # the SDL3 VC development package, unpacked
# the graphics back end on Windows: Direct3D 12, its shaders generated as HLSL and compiled at run time
GFX_SOURCES = ['runtime\\portable\\gfx_hlsl.c', 'runtime\\portable\\gfx_hlsl_shaders.c', 'runtime\\portable\\gfx_d3d12.c']
GFX_LIBS = ['d3d12.lib', 'dxgi.lib', 'd3dcompiler.lib', 'dxguid.lib']
HOST_BASE = ['runtime\\portable\\user32.c', 'runtime\\portable\\d3d8.c', 'runtime\\portable\\dsound.c',
             'runtime\\portable\\input.c', 'runtime\\portable\\dinput.c', 'runtime\\portable\\ws2.c', 'host\\host64.c',
             'host\\lsb_login.c', 'host\\datui.c', 'host\\uidraw.c', 'host\\modern.c', 'host\\discord.c', 'host\\signin.c', 'host\\sewave.c', 'host\\ui_art.c',
             'host\\keychain.c', 'host\\appdefaults.c', 'runtime\\portable\\sampler_win.c']
HOST_SOURCES = HOST_BASE + GFX_SOURCES
# the sign-in screen's: stb_image
HOST_INCLUDES = ['/I', 'third_party\\stb']
# the sign-in screen itself (host/signin.c), the Modern panel (host/modern.c) and what only they use
SIGNIN_SCREEN = ['host\\signin.c', 'host\\sewave.c', 'host\\modern.c', 'host\\datui.c', 'host\\uidraw.c', 'host\\ui_art.c']
# the LandSandBoat sign-in's TLS is SChannel here (secur32.lib); mbedtls on POSIX hosts
HOST_LIBS = ['synchronization.lib', 'ws2_32.lib', 'advapi32.lib', 'bcrypt.lib', 'secur32.lib'] + GFX_LIBS


# The addon host (host/addons/, docs/addon-compat-design.md): its C and C++ sources, the embedded Lua
# (tools/embed_lua.py), and the vendored libraries it links: LuaJIT (its own msvcbuild.bat, in a copy of
# its tree), Dear ImGui, LuaSocket (Winsock back end) and LuaFileSystem.
ADDON_DIR = os.path.join(ROOT, 'host', 'addons')
IMGUI = ['third_party\\imgui\\' + f for f in ('imgui.cpp', 'imgui_draw.cpp', 'imgui_tables.cpp', 'imgui_widgets.cpp',
                                                'imgui_demo.cpp')] + ['third_party\\imgui\\misc\\cpp\\imgui_stdlib.cpp']
LUASOCKET = ['third_party\\luasocket\\src\\' + f for f in ('luasocket.c', 'timeout.c', 'buffer.c', 'io.c', 'auxiliar.c',
                                                              'compat.c', 'options.c', 'inet.c', 'except.c', 'select.c', 'tcp.c',
                                                              'udp.c', 'wsocket.c', 'mime.c')]
ADDON_INCLUDES = ['/I', 'host\\addons', '/I', 'third_party\\luajit\\src', '/I', 'third_party\\imgui', '/I',
                  'third_party\\luasocket\\src', '/I', 'third_party\\lfs', '/DIMGUI_USER_CONFIG="imconfig_xi.h"',
                  '/D_CRT_SECURE_NO_WARNINGS', '/DLUASOCKET_NODEBUG']


def luajit(env, uwp):
    """LuaJIT as a static library (with our parser patch, Lua 5.2 compatibility), built by its own
    msvcbuild.bat in a copy of third_party/luajit. The UWP app's has the dynamic CRT and no JIT: a
    packaged app without the codeGeneration capability may not make executable memory."""
    work = os.path.join(ROOT, 'build', 'third_party', 'luajit-uwp' if uwp else 'luajit-win')
    lib = os.path.join(work, 'src', 'lua51.lib')
    src_tree = os.path.join(ROOT, 'third_party', 'luajit')
    newest = max(os.path.getmtime(os.path.join(d, f)) for d, _, fs in os.walk(src_tree) for f in fs)
    if os.path.exists(lib) and os.path.getmtime(lib) >= newest:
        return lib
    if os.path.exists(work):
        shutil.rmtree(work)
    shutil.copytree(src_tree, work)
    bat = os.path.join(work, 'src', 'msvcbuild.bat')
    text = open(bat).read()
    extra = ' /MD /DLUAJIT_DISABLE_JIT' if uwp else ' /MT'
    text = text.replace('@set LJCOMPILE=cl /nologo /c /O2 /W3', '@set LJCOMPILE=cl /nologo /c /O2 /W3' + extra, 1)
    open(bat, 'w').write(text)
    print('> msvcbuild.bat lua52compat static (%s)' % ('uwp' if uwp else 'win'))
    # msvcbuild.bat runs itself and the tools it builds (minilua, buildvm) from the current folder,
    # which cmd refuses when NoDefaultCurrentDirectoryInExePath is set
    env = {k: v for k, v in env.items() if k.lower() != 'nodefaultcurrentdirectoryinexepath'}
    subprocess.check_call(['cmd', '/c', 'msvcbuild.bat', 'lua52compat', 'static'], cwd=os.path.join(work, 'src'), env=env)
    return lib


def addon_objects(env, cflags, objdir, uwp=False):
    """The addon host's objects and LuaJIT's library, compiled with the host's C flags (C++: the same
    runtime, C++17)."""
    run([sys.executable, 'tools/embed_lua.py'])
    names = sorted(os.listdir(ADDON_DIR))
    c = ['host\\addons\\' + f for f in names if f.endswith('.c')] + ['generated\\addons_lua.c']
    cpp = ['host\\addons\\' + f for f in names if f.endswith('.cpp')]
    sdl_inc = ['/I', os.path.join(SDL3, 'include')]
    cxx = [f for f in cflags if f != '/std:c11'] + ['/std:c++17', '/EHsc', '/Zc:__cplusplus']
    objs = compile_stale(env, c, objdir + '\\addons', ADDON_INCLUDES + sdl_inc + HOST_INCLUDES + ['/I', 'runtime\\portable'], cflags)
    objs += compile_stale(env, cpp, objdir + '\\addons_cpp', ADDON_INCLUDES + sdl_inc + HOST_INCLUDES + ['/I', 'runtime\\portable'], cxx)
    objs += compile_stale(env, IMGUI, objdir + '\\imgui', ADDON_INCLUDES, cxx)
    objs += compile_stale(env, LUASOCKET, objdir + '\\luasocket', ADDON_INCLUDES, cflags)
    # without LuaSocket's src/ on the path: its io.h would stand in for the CRT's, which lfs needs here
    lfs_inc = ['/I', 'third_party\\luajit\\src', '/D_CRT_SECURE_NO_WARNINGS']
    objs += compile_stale(env, ['third_party\\lfs\\lfs.c'], objdir + '\\lfs', lfs_inc, cflags)
    # SQLite and its Lua binding (Windower's sqlite3 module)
    objs += compile_stale(env, ['third_party\\sqlite\\sqlite3.c', 'third_party\\sqlite\\lsqlite3\\lsqlite3.c'], objdir + '\\sqlite',
                          ADDON_INCLUDES + ['/I', 'third_party\\sqlite', '/DSQLITE_THREADSAFE=0', '/DSQLITE_OMIT_LOAD_EXTENSION'], cflags)
    return objs + [luajit(env, uwp)]


def sdl3():
    """SDL3's include flags and import library."""
    if not os.path.exists(os.path.join(SDL3, 'include', 'SDL3', 'SDL.h')):
        raise SystemExit('SDL3 not found at %s: unpack SDL3-devel-<version>-VC.zip there, or set SDL3_DIR' % SDL3)
    return ['/I', os.path.join(SDL3, 'include')], os.path.join(SDL3, 'lib', 'x64', 'SDL3.lib')


def translate():
    """FFXiMain and FFXi.dll translated to C (only the files whose text changed are rewritten)."""
    recomp('generated/all', ['--all'])
    run([sys.executable, 'recomp/recomp.py', '--meta', FFXI_META, '--image', FFXI_IMAGE, '--retail',
         FFXI_RETAIL, '--module', 'ffxi', '--out', 'generated/ffxi', '--all'])


def game_objects(env):
    """FFXiMain and FFXi.dll translated and compiled: the objects every 64-bit host links."""
    translate()
    gen = ['generated\\all\\' + f for f in sorted(os.listdir(os.path.join(ROOT, 'generated', 'all'))) if f.endswith('.c')]
    gen_ffxi = ['generated\\ffxi\\' + f for f in sorted(os.listdir(os.path.join(ROOT, 'generated', 'ffxi'))) if f.endswith('.c')]
    objs = compile_stale(env, gen, 'build\\all64', ['/I', 'generated\\all'], CFLAGS64)
    objs += compile_stale(env, gen_ffxi, 'build\\ffxi64', ['/I', 'generated\\ffxi'], CFLAGS64)
    return objs


def host_resources(env, objdir):
    """host/host64.rc (the game's icon and the file's description) as a .res for link."""
    res = os.path.join(objdir, 'host64.res')
    os.makedirs(os.path.join(ROOT, objdir), exist_ok=True)
    run(['rc', '/nologo', '/fo', res, 'host\\host64.rc'], env)
    return res


def host64(env):
    """The 64-bit game host: FFXiMain and FFXi.dll translated, the portable runtime, SDL3."""
    objs = game_objects(env)
    sdl_inc, sdl_lib = sdl3()
    objs += compile_stale(env, PORTABLE + HOST_SOURCES, 'build\\host64', sdl_inc + HOST_INCLUDES, CFLAGS64)
    objs += addon_objects(env, CFLAGS64, 'build\\host64')
    # Addons' ffi.C looks in the exe's own exports first, then the CRT, kernel32, user32 and gdi32: the
    # D3DX and gdifonts stand-ins (host/addons/d3d_ffi.c, gdifont_ffi.c) are __declspec(dllexport), so
    # host64.exe exports them (link also writes an import .lib/.exp nobody needs). Win32 functions are the
    # real ones (win32_ffi.c is empty on Windows); ones in other DLLs (winmm's PlaySound, shell32) need
    # xi.lua to ffi.load the real DLL there rather than map it to ffi.C.
    objs.append(host_resources(env, 'build\\host64'))
    run(['link', '/nologo', '/OUT:build\\host64.exe', '/MACHINE:X64', sdl_lib] + HOST_LIBS + objs, env)
    shutil.copy(os.path.join(SDL3, 'lib', 'x64', 'SDL3.dll'), os.path.join(ROOT, 'build'))
    buildinfo.stamp(os.path.join(ROOT, 'build', 'runtime.json'))
    print('built build\\host64.exe; run: build\\host64.exe --game "%s" ...' % BUILD['game'])


def host64_headless(env):
    """host64 with the null graphics back end: nothing drawn, the frame profile kept (FFXI_PROFILE=1)."""
    objs = game_objects(env)
    sdl_inc, sdl_lib = sdl3()
    objs += compile_stale(env, PORTABLE + HOST_BASE + ['runtime\\portable\\gfx_null.c'], 'build\\headless', sdl_inc + HOST_INCLUDES,
                          CFLAGS64)
    libs = [lib for lib in HOST_LIBS if lib not in GFX_LIBS]
    objs.append(host_resources(env, 'build\\headless'))
    run(['link', '/nologo', '/OUT:build\\host64-headless.exe', '/MACHINE:X64', sdl_lib] + libs + objs, env)
    shutil.copy(os.path.join(SDL3, 'lib', 'x64', 'SDL3.dll'), os.path.join(ROOT, 'build'))
    print('built build\\host64-headless.exe')


# The UWP app (FFXIXbox) links the game as a library: the dynamic CRT (/MD) that UWP apps must use, no
# SDL3 (sdl_uwp.c in its place; SDL3's headers still give the types), the sign-in's TLS from the app,
# and host64's main renamed host_main for the app to call. Which Win32 calls UWP allows is checked
# when the app links, against WindowsApp.lib alone.
UWP_CFLAGS = [f for f in CFLAGS64 if f != '/MT'] + ['/MD', '/DFFXI_UWP']


def uwp_lib(env):
    """build/uwp/ffxi_uwp.lib: host64 for the UWP app, drawing with Direct3D 12 into its SwapChainPanel."""
    translate()
    gen = ['generated\\all\\' + f for f in sorted(os.listdir(os.path.join(ROOT, 'generated', 'all'))) if f.endswith('.c')]
    gen_ffxi = ['generated\\ffxi\\' + f for f in sorted(os.listdir(os.path.join(ROOT, 'generated', 'ffxi'))) if f.endswith('.c')]
    objs = compile_stale(env, gen, 'build\\uwp\\all', ['/I', 'generated\\all'], UWP_CFLAGS)
    objs += compile_stale(env, gen_ffxi, 'build\\uwp\\ffxi', ['/I', 'generated\\ffxi'], UWP_CFLAGS)
    sdl_inc = ['/I', os.path.join(SDL3, 'include')]
    # the app signs in itself (its own login screen): no sign-in screen
    host = [s for s in HOST_SOURCES if s not in SIGNIN_SCREEN] + ['host\\signin_none.c', 'runtime\\portable\\sdl_uwp.c']
    objs += compile_stale(env, PORTABLE + host, 'build\\uwp\\host', sdl_inc + ['/Dmain=host_main'], UWP_CFLAGS)
    objs += addon_objects(env, UWP_CFLAGS, 'build\\uwp', uwp=True)
    run(['lib', '/nologo', '/OUT:build\\uwp\\ffxi_uwp.lib'] + objs, env)
    print('built build\\uwp\\ffxi_uwp.lib')


def gfxtest(env):
    """The back end alone (gfx_test), then the D3D8 front end on it through its COM thunks (d3d8_test)."""
    sdl_inc, sdl_lib = sdl3()
    objs = compile_stale(env, GFX_SOURCES + ['tests\\gfx_test.c'], 'build\\gfxtest', sdl_inc, CFLAGS64)
    run(['link', '/nologo', '/OUT:build\\gfx_test.exe', '/MACHINE:X64', sdl_lib] + GFX_LIBS + objs, env)
    shutil.copy(os.path.join(SDL3, 'lib', 'x64', 'SDL3.dll'), os.path.join(ROOT, 'build'))
    run(['build\\gfx_test.exe'], env)
    objs = compile_stale(env, PORTABLE + GFX_SOURCES + ['runtime\\portable\\user32.c', 'runtime\\portable\\input.c',
                                                        'runtime\\portable\\d3d8.c', 'tests\\d3d8_test.c'],
                         'build\\d3d8test', sdl_inc, CFLAGS64)
    run(['link', '/nologo', '/OUT:build\\d3d8_test.exe', '/MACHINE:X64', sdl_lib, 'synchronization.lib', 'advapi32.lib']
        + GFX_LIBS + objs, env)
    run(['build\\d3d8_test.exe'], env)


def main():
    what = sys.argv[1] if len(sys.argv) > 1 else 'difftest'
    targets = {'difftest': difftest, 'host': host, 'boot64': boot64, 'host64': host64,
               'host64-headless': host64_headless, 'uwp-lib': uwp_lib, 'gfxtest': gfxtest}
    if what not in targets:
        raise SystemExit('targets: ' + ', '.join(targets))
    env = msvc_env('x64' if what in ('boot64', 'host64', 'host64-headless', 'uwp-lib', 'gfxtest') else 'x86')
    if what != 'gfxtest':  # the others translate the game: they need the build prepare.py chose
        if BUILD is None:
            buildinfo.current()  # exits: run tools/prepare.py first
        write_build_h()
    targets[what](env)


if __name__ == '__main__':
    main()
